apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: node-github 
  janus-idp.io/tekton: node-github
  backstage.io/kubernetes-id: node-github
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: node-github
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  